// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalproject.Data;

#nullable disable

namespace finalproject.Migrations
{
    [DbContext(typeof(finalprojectContext))]
    [Migration("20220605150959_MysecMigration")]
    partial class MysecMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("finalproject.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Iso3")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("iso3");

                    b.Property<string>("code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("finalproject.Models.Pop", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Countryid")
                        .HasColumnType("int")
                        .HasColumnName("countryid");

                    b.Property<long>("value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.Property<int>("year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Countryid" }, "countryid");

                    b.ToTable("pops", (string)null);
                });

            modelBuilder.Entity("finalproject.Models.Pop", b =>
                {
                    b.HasOne("finalproject.Models.Countries", "Country")
                        .WithMany("populationCounts")
                        .HasForeignKey("Countryid")
                        .IsRequired()
                        .HasConstraintName("pops_ibfk_1");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("finalproject.Models.Countries", b =>
                {
                    b.Navigation("populationCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
